spring:
  datasource:
    url : jdbc:h2:tcp://localhost/~/jpashop;MVXX=TRUE
    username : sa
    password :
    driver-class-name: org.h2.driver
  jpa:
    hibernate:
      ddl-auto: create
#      table을 자동으로 만들어는 모드
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug